### ISSUE TITLE
node dist/pack/package-function-app.js functionapp.zip not working

### ISSUE THREAD

**Issue by b2infosoft-manoj** [NordicSemiconductor/asset-tracker-cloud-azure-js#303]
Hi,
Please help, command node dist/pack/package-function-app.js functionapp.zip is not working, not creating any fucntionapp.zip file

**Comment by coderbyheart** [comment]
Hei @keyss-manoj, thanks for reporting!

I think this is a documentation error, it should be this command

```bash
node scripts/pack-app.js
```

Reference: https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/blob/0f1715ee534935134c3ab10619a106dc87d295eb/.github/workflows/cd.yaml#L184-L185

**Comment by coderbyheart** [comment]
The next step then should be 

```bash
    az functionapp deployment source config-zip -g ${RESOURCE_GROUP:-nrfassettracker} -n ${APP_NAME:-nrfassettracker}api --src dist/functionapp.zip
```
