### ISSUE TITLE
node scripts/pack-app.js not working on Windows

### ISSUE THREAD

**Issue by b2infosoft-manoj** [NordicSemiconductor/asset-tracker-cloud-azure-js#304]
Hi,
I tried to run node scripts/pack-app.js command but getting below error message, could you please check for me.
$ node scripts/pack-app.js
Packaging to C:\Users\manoj\nrf-asset-tracker\azure\dist\functionapp.zip
Packaging function agpsDeviceRequestsHandler
Packaging function agpsQueuedDeviceRequestsHandler
Packaging function agpsResolveRequestFromNrfCloud
Packaging function deleteDevice
Packaging function geolocateCell
Packaging function geolocateCellFromNrfCloud
Packaging function geolocateCellFromUnwiredLabs
Packaging function geolocateNcellmeasReportFromNrfCloud
Packaging function getDevice
Packaging function getSignalRConnectionInfo
Packaging function listDevices
Packaging function pgpsDeviceRequestsHandler
Packaging function pgpsQueuedDeviceRequestsHandler
Packaging function pgpsResolveRequestFromNrfCloud
Packaging function publishDeviceUpdatesToSignalR
Packaging function queryHistoricalDeviceData
Packaging function queryNcellmeasReport
Packaging function storeDeviceCellGeolocation
Packaging function storeDeviceUpdateInCosmosDB
Packaging function storeDeviceUpgrade
Packaging function storeImage
Packaging function storeNcellmeasReportInCosmosDb
Packaging function updateDevice
[copy] C:\Users\manoj\nrf-asset-tracker\azure\host.json -> C:\Users\manoj\AppData\Local\Temp\ZA5fC4\host.json
[copy] C:\Users\manoj\nrf-asset-tracker\azure\package.json -> C:\Users\manoj\AppData\Local\Temp\ZA5fC4\package.json
[copy] C:\Users\manoj\nrf-asset-tracker\azure\package-lock.json -> C:\Users\manoj\AppData\Local\Temp\ZA5fC4\package-l
ock.json
Installing dependencies npm ci --ignore-scripts --only=prod --no-audit
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'ci', '--ignore-scripts', '--only=prod', '--no-audit' ]
}

Node.js v17.6.0

**Comment by coderbyheart** [comment]
Hei, Windows is currently not tested / supported, so sorry for that.

1. Please upvote [this entry to voice your request for Window support](https://github.com/NordicSemiconductor/asset-tracker-cloud-docs/discussions/21)
2. It seems that `npm` is not installed or available in your path, please ensure that it is. You should be able to run `npm` from your terminal: `npm --version`

**Comment by b2infosoft-manoj** [comment]
npm is looking on my path
$ npm --version
7.0.0

**Comment by coderbyheart** [comment]
As [per the docs](https://nordicsemiconductor.github.io/asset-tracker-cloud-docs/saga/docs/project/SystemRequirements.html#system-requirements), please ensure you have npm version 8 installed.

**Comment by coderbyheart** [comment]
Could you apply this patch to [the code](https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/blob/e41ab92829231e60018e69cd7c00fbe9c40f0b1d/pack/package-function-app.ts#L47):

```diff
-		command: 'npm',
+		command: 'npm.cmd',
```

Compile it (`npx tsc`) and run it again?

**Comment by b2infosoft-manoj** [comment]
npm now update to 8.5.3
also applied patch and compile
getting now below error
[ZIP] zip -r C:\Users\manoj\nrf-asset-tracker\azure\dist\functionapp.zip ./
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn zip ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn zip',
  path: 'zip',
  spawnargs: [
    '-r',
    'C:\\Users\\manoj\\nrf-asset-tracker\\azure\\dist\\functionapp.zip',
    './'
  ]
}

Node.js v17.6.0

**Comment by coderbyheart** [comment]
Ah, great, we are getting somewhere. I guess this is a similar issue, try replacing `zip` with `zip.exe`.

**Comment by b2infosoft-manoj** [comment]
no luck! 
[ZIP] zip.exe -r C:\Users\manoj\nrf-asset-tracker\azure\dist\functionapp.zip ./
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn zip.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn zip.exe',
  path: 'zip.exe',
  spawnargs: [
    '-r',
    'C:\\Users\\manoj\\nrf-asset-tracker\\azure\\dist\\functionapp.zip',
    './'
  ]
}

Node.js v17.6.0

**Comment by coderbyheart** [comment]
Is `zip.exe` available in your path?

**Comment by b2infosoft-manoj** [comment]
I did not install any zip application but by default window provide option to archive directory so not sure what application it use to compress, do you have any idea?

**Comment by coderbyheart** [comment]
I guess for Windows we need a different approach: https://superuser.com/questions/1430205/why-doesnt-windows-have-a-command-line-zip-command

**Comment by b2infosoft-manoj** [comment]
yes, I think so, I installed 7-Zip and set path but still same issue, could you please update code so that I can apply same thing?

**Comment by coderbyheart** [comment]
What did you change to make 7zip work? `7z` has different command line arguments than `zip`.

**Comment by coderbyheart** [comment]
I've looked through the codebase, and there are many more uses of Unix tools (for example OpenSSL), which also won't work on native Windows. 

I am closing this, because right now as per our system requirements, native Windows is not supported, use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) with [Ubuntu 20.04 LTS](https://www.microsoft.com/nb-no/p/ubuntu-2004-lts/9n6svws3rx71).
