### ISSUE TITLE
Migrate off `@azure/ms-rest-js`

### ISSUE THREAD

**Issue by jeremymeng** [NordicSemiconductor/asset-tracker-cloud-azure-js#589]
I found dependency on `@azure/ms-rest-js` but don't see any useage.

https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/blob/bff781fd34cc86afe8d3b6993a1d08389a764e7c/package.json#L33

`@azure/ms-rest-js` is no longer actively maintained.  Free free to reach out if you have any questions.

**Comment by coderbyheart** [comment]
Thanks!
